"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, Apple, CalendarDays, Check, ChevronLeft, CirclePlus, Dumbbell, MoreHorizontal, Pencil, Settings, Trash2, TrendingUp, X } from "lucide-react";
import { useStore } from "@/lib/store";
import { STORE_KEY, INIT, uid } from "../model";
import css from "./health-v2.module.css";

const NAV = [
  ["today", "היום", Activity],
  ["journal", "תיעוד", CirclePlus],
  ["plan", "תוכנית", CalendarDays],
  ["progress", "התקדמות", TrendingUp],
];
const localISO = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
const fmt = value => new Date(value + "T12:00").toLocaleDateString("he-IL", { weekday:"short", day:"numeric", month:"short" });
const addDays = (n) => { const d = new Date(); d.setDate(d.getDate() + n); return d.toISOString().slice(0,10); };

function Empty({ children }) { return <div className={css.empty}>{children}</div>; }
function IconButton({ label, children, ...props }) { return <button aria-label={label} className={css.iconButton} {...props}>{children}</button>; }
function Header({ setTab }) { return <header className={css.header}><div><Link href="/" className={css.back}>חזרה למנכ״ל</Link><p className={css.eyebrow}>מרחב האימון והתזונה שלך</p><h1 className={css.title}>אימון ותזונה</h1></div><button onClick={()=>setTab("settings")} className={css.profileButton}>הפרופיל שלי</button></header>; }
function Nav({ tab, onNavigate }) { return <><aside className={css.desktopAside}>{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>onNavigate(id)} className={tab===id?css.active:""}><Icon size={18}/> {label}</button>)}</aside><nav className={css.bottomNav} aria-label="ניווט חברת אימון ותזונה">{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>onNavigate(id)} className={css.navItem+" "+(tab===id?css.active:"")} aria-current={tab===id?"page":undefined}><Icon/><span>{label}</span></button>)}</nav></>; }

function Onboarding({ d, setD }) {
  const steps = [
    { key:"goal", title:"מה חשוב לך להשיג?", help:"אפשר לבחור יותר ממטרה אחת.", multi:true, options:["להיכנס לכושר לקראת החתונה","לבנות כוח ומסת שריר","לרדת במשקל","לחזור לכושר","להרגיש יותר אנרגיה","לשפר ביטחון עצמי","לשפר סיבולת"] },
    { key:"focus", title:"מה תרצה/י לכלול בתוכנית?", help:"אפשר לבחור כמה כיוונים.", multi:true, options:["אימוני כוח","כושר אירובי","ניידות וגמישות","תזונה והרגלים","שילוב מאוזן","רק להתחיל בעדינות"] },
    { key:"experience", title:"מה נקודת הפתיחה שלך?", help:"בחירה אחת שתעזור לקבוע קצב התחלתי.", options:["מתחיל/ה מאפס","חוזר/ת אחרי הפסקה","מתאמן/ת לסירוגין","מתאמן/ת קבוע"] },
    { key:"place", title:"איפה נוח לך להתאמן?", help:"אפשר לבחור יותר מאפשרות אחת.", multi:true, options:["חדר כושר","בבית עם ציוד","בבית בלי ציוד","בחוץ","סטודיו או קבוצה"] },
    { key:"availability", title:"כמה אימונים ריאליים בשבוע?", help:"נבנה סביב מה שאפשר לשמור עליו.", options:["1","2","3","4","5 או יותר","עדיין לא יודע/ת"] },
    { key:"sessionLength", title:"כמה זמן יש לך לאימון?", help:"נעדיף זמן אמיתי על תוכנית מושלמת.", options:["10–15 דקות","20–30 דקות","40–45 דקות","שעה או יותר","משתנה"] },
    { key:"trainingDays", title:"באילו ימים בדרך כלל אפשר?", help:"אפשר לבחור כמה ימים; אפשר לשנות בכל שבוע.", multi:true, options:["א׳","ב׳","ג׳","ד׳","ה׳","ו׳","שבת","משתנה"] },
    { key:"trainingTime", title:"מתי הכי נוח לך להתאמן?", help:"אפשר לבחור יותר מחלון זמן אחד.", multi:true, options:["בוקר","צהריים","ערב","לילה","משתנה"] },
    { key:"comfort", title:"איזה סגנון מרגיש לך נכון?", help:"המערכת תעדיף פעולות שמתאימות לך.", options:["קצר ופשוט","מובנה ומסודר","גמיש לפי היום","עם תזכורות","לנסות ולגלות"] },
    { key:"likes", title:"אילו פעילויות אתה אוהב?", help:"אפשר לבחור כמה, כדי שהתוכנית תהיה כזו שתרצה באמת לבצע.", multi:true, options:["הליכה","ריצה","אימוני כוח","מכונות","משקולות חופשיים","תרגילי משקל גוף","אופניים","שחייה","יוגה / פילאטיס"] },
    { key:"dislikes", title:"מה פחות מתאים לך?", help:"אפשר לבחור כמה; נמנע מלהכניס אותם כברירת מחדל.", multi:true, options:["ריצה","קפיצות","תרגילים על הרצפה","חדר כושר עמוס","אימונים ארוכים","אימוני קבוצה","לא בטוח/ה"] },
    { key:"stepsBaseline", title:"כמה צעדים יש לך ביום ממוצע?", help:"זה רק קו פתיחה ליעד אישי שניתן לשנות.", options:["עד 3,000","3,000–5,000","5,000–7,500","7,500–10,000","מעל 10,000","לא יודע/ת"] },
    { key:"safety", title:"יש משהו שחשוב לקחת בחשבון?", help:"אם יש כאב, פציעה או מגבלה — לא בונים כאן תוכנית מותאמת. כדאי להתייעץ עם איש/ת מקצוע.", options:["לא ידוע לי על מגבלה","יש מגבלה ואני מתייעץ/ת עם איש מקצוע","לא בטוח/ה"] },
  ];
  const [step, setStep] = useState(Math.min(d.profile.onboardingStep || 0, steps.length - 1));
  const [draft, setDraft] = useState(d.profile);
  const [attempted, setAttempted] = useState(false);
  const current = steps[step];
  const selectedValues = Array.isArray(draft[current.key]) ? draft[current.key] : draft[current.key] ? [draft[current.key]] : [];
  const hasSelection = selectedValues.length > 0;
  const select = value => setDraft(profile => {
    const old = Array.isArray(profile[current.key]) ? profile[current.key] : profile[current.key] ? [profile[current.key]] : [];
    return { ...profile, [current.key]: current.multi ? (old.includes(value) ? old.filter(item => item !== value) : [...old, value]) : value };
  });
  const persist = nextStep => { setD(data => ({ ...data, profile:{ ...data.profile, ...draft, onboardingStep:nextStep } })); setStep(nextStep); };
  const next = () => { if (!hasSelection) { setAttempted(true); return; } setAttempted(false); if (step < steps.length - 1) persist(step + 1); else setD(data => ({ ...data, profile:{ ...data.profile, ...draft, onboardingStep:steps.length, complete:true } })); };
  const previous = () => { if (step > 0) { setAttempted(false); persist(step - 1); } };
  return <main className={css.onboard}>
    <Link href="/" className={css.back}>חזרה למנכ״ל</Link>
    <p className={css.eyebrow}>פרופיל האימונים שלך · {step + 1} מתוך {steps.length}</p>
    <div className={css.progressLine}>{steps.map((_,i) => <i key={i} className={i <= step ? css.done : ""} />)}</div>
    <section className={css.card+" "+css.stack}>
      <h2 className={css.title}>{current.title}</h2><p className={css.subtle}>{current.help}</p>
      <div className={css.choiceGrid}>{current.options.map(value => <button key={value} aria-pressed={selectedValues.includes(value)} onClick={() => {setAttempted(false);select(value)}} className={css.choice+" "+(selectedValues.includes(value) ? css.selected : "")}>{value}</button>)}</div>
      {attempted && <p className={css.validation} role="alert">כדי להמשיך, צריך לבחור לפחות אפשרות אחת.</p>}
      <div className={css.onboardingActions}>{step > 0 && <button className={css.secondary} onClick={previous}>חזרה</button>}<button className={css.primary} onClick={next}>{step === steps.length - 1 ? "בניית התוכנית" : "המשך"}<ChevronLeft size={18}/></button></div>
    </section>
  </main>;
}
function Today({ d, setD, setTab, setComposer }) {
  const dayModes = d.dayModes || [];
  const selectedMode = dayModes.find(item => item.date === localISO())?.mode || "";
  const chooseMode = mode => setD(p => ({ ...p, dayModes: [...(p.dayModes || []).filter(item => item.date !== localISO()), { date: localISO(), mode }] }));
  const modeAction = selectedMode === "short" ? () => setComposer("walk") : selectedMode === "time" ? () => setTab("plan") : () => setComposer("food");
  const modeLabel = selectedMode === "short" ? "יש לי 5 דקות" : selectedMode === "time" ? "יש לי זמן להשקיע" : "יום עמוס — רק לשמור על קשר";
  const today=localISO(), meals=d.meals.filter(x=>x.date===today).length, workouts=d.workouts.filter(x=>x.date===today&&!x.skipped).length;
  const due=(d.plan||[]).filter(x=>x.date===today&&x.status!=="done").slice(0,2);
  const message=meals||workouts ? "נרשם משהו היום. אפשר להמשיך רק אם זה מתאים." : "אין צורך להספיק הכול. פעולה קטנה אחת מספיקה.";
  return <><section className={css.card+" "+css.hero}><p className={css.eyebrow}>היום · {fmt(today)}</p><h2>{message}</h2><p>{d.profile.goal ? "המטרה שבחרת: "+d.profile.goal+(d.profile.focus ? " · מיקוד: "+d.profile.focus : "") : "אפשר להתחיל בתיעוד קצר, בלי לבנות הכול עכשיו."}</p><button className={css.primary+" "+css.mint} onClick={modeAction}>{selectedMode === "short" ? "תיעוד הליכה" : selectedMode === "time" ? "לפעולות שלי" : "תיעוד מהיר"} <CirclePlus size={18}/></button></section>
  {!selectedMode ? <section className={css.card+" "+css.stack}><div><strong>מה מתאים לך היום?</strong><p className={css.subtle}>הבחירה רק עוזרת להתמקד בפעולה אחת.</p></div><div className={css.dayChoices}><button onClick={()=>chooseMode("short")}>יש לי 5 דקות</button><button onClick={()=>chooseMode("time")}>יש לי זמן להשקיע</button><button onClick={()=>chooseMode("busy")}>יום עמוס</button></div></section> : <div className={css.modeNote}><span>היום בחרת: {modeLabel}</span><button onClick={()=>chooseMode("")}>לשנות</button></div>}
  <div className={css.quickGrid}><button className={css.quick+" "+css.food} onClick={()=>setComposer("food")}><Apple size={23}/><strong>אוכל</strong><span>{meals?meals+" תיעודים היום":"לתעד מה היה"}</span></button><button className={css.quick+" "+css.move} onClick={()=>setComposer("move")}><Dumbbell size={23}/><strong>תנועה</strong><span>{workouts?workouts+" פעילויות היום":"לתעד תנועה"}</span></button></div>
  <div className={css.sectionHead}><h2>מה בתוכנית להיום</h2><button className={css.linkButton} onClick={()=>setTab("plan")}>לכל התוכנית</button></div>
  <section className={css.card}>{due.length?due.map(item=><div className={css.next} key={item.id}><span className={css.nextIcon}><CalendarDays size={19}/></span><div><strong>{item.text}</strong><span>{item.kind==="food"?"תזונה":"תנועה"} · גמיש לשינוי</span></div></div>):<Empty>עוד אין פעולה מתוכננת להיום.<br/>אפשר להוסיף משהו קטן לתוכנית.</Empty>}</section></>;
}
function Composer({ kind, onClose, d, setD, onSaved }) {
  const [type,setType]=useState(kind === "walk" ? "move" : kind || "food"),[more,setMore]=useState(false),[draft,setDraft]=useState({name:kind === "walk" ? "הליכה" : "",date:localISO(),duration:"",note:"",feeling:""});
  const save=e=>{e.preventDefault();if(!draft.name.trim())return; const item={...draft,id:uid(),createdAt:new Date().toISOString()};setD(p=>type==="food"?{...p,meals:[item,...p.meals]}:{...p,workouts:[item,...p.workouts]});onSaved(type==="food"?"הארוחה נרשמה.":"הפעילות נרשמה.");};
  return <section className={css.composer}><div className={css.composerHead}><h2>תיעוד מהיר</h2><IconButton label="סגירה" onClick={onClose}><X size={18}/></IconButton></div><div className={css.toggle}><button onClick={()=>setType("food")} className={type==="food"?css.active:""}>🍽️ אוכל</button><button onClick={()=>setType("move")} className={type==="move"?css.active:""}>🚶 תנועה</button></div><form className={css.form} onSubmit={save}><label>{type==="food"?"מה היה?":"מה עשית?"}<input autoFocus className={css.field} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder={type==="food"?"למשל כריך, קפה או ארוחה בבית":"למשל הליכה, חדר כושר או מתיחות"}/></label>{type==="move"&&<label>משך, אם מתאים<select className={css.field} value={draft.duration} onChange={e=>setDraft({...draft,duration:e.target.value})}><option value="">לא לציין</option><option>10 דקות</option><option>20 דקות</option><option>30 דקות</option><option>אחר</option></select></label>}<button type="button" className={css.optional} onClick={()=>setMore(!more)}>{more?"פחות פרטים":"הוספת פרטים"}</button>{more&&<><label>תאריך<input className={css.field} dir="ltr" type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>איך הרגיש לך?<select className={css.field} value={draft.feeling} onChange={e=>setDraft({...draft,feeling:e.target.value})}><option value="">לא לציין</option><option>טוב</option><option>סביר</option><option>מאתגר</option><option>לא בטוח/ה</option></select></label><label>הערה<textarea className={css.field} value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})}/></label></>}<button className={css.primary+" "+css.wide} type="submit">שמירה</button></form></section>;
}
function Journal({ d, setD, setComposer, remove }) {
  const [filter,setFilter]=useState("all"), [edit,setEdit]=useState(null);
  const entries=useMemo(()=>[...d.meals.map(x=>({...x,type:"food"})),...d.workouts.map(x=>({...x,type:"move"}))].filter(x=>filter==="all"||x.type===filter).sort((a,b)=>(b.date||"").localeCompare(a.date||"")),[d,filter]);
  const grouped=entries.reduce((acc,x)=>{const key=x.date||localISO();(acc[key]??=[]).push(x);return acc;},{});
  const saveEdit=e=>{e.preventDefault();if(!edit.name.trim())return;setD(p=>edit.type==="food"?{...p,meals:p.meals.map(x=>x.id===edit.id?edit:x)}:{...p,workouts:p.workouts.map(x=>x.id===edit.id?edit:x)});setEdit(null);};
  if(edit)return <section className={css.composer}><div className={css.composerHead}><h2>עריכת תיעוד</h2><IconButton label="סגירה" onClick={()=>setEdit(null)}><X/></IconButton></div><form className={css.form} onSubmit={saveEdit}><label>מה היה?<input className={css.field} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><div className={css.row}><label>תאריך<input className={css.field} dir="ltr" type="date" value={edit.date} onChange={e=>setEdit({...edit,date:e.target.value})}/></label>{edit.type==="move"&&<label>משך<input className={css.field} value={edit.duration||""} onChange={e=>setEdit({...edit,duration:e.target.value})}/></label>}</div><label>הערה<textarea className={css.field} value={edit.note||""} onChange={e=>setEdit({...edit,note:e.target.value})}/></label><button className={css.primary+" "+css.wide}>שמירת שינויים</button></form></section>;
  return <><div className={css.sectionHead}><h2>היומן שלך</h2><button className={css.primary} onClick={()=>setComposer("food")}><CirclePlus size={17}/> תיעוד</button></div><div className={css.journalTabs}><button className={filter==="all"?css.active:""} onClick={()=>setFilter("all")}>הכול</button><button className={filter==="food"?css.active:""} onClick={()=>setFilter("food")}>אוכל</button><button className={filter==="move"?css.active:""} onClick={()=>setFilter("move")}>תנועה</button></div><section className={css.card}>{!entries.length?<Empty>עוד לא נרשם דבר.<br/>אפשר להתחיל בארוחה או בתנועה אחת.</Empty>:Object.entries(grouped).map(([date,items])=><div key={date}><p className={css.eyebrow}>{fmt(date)}</p>{items.map(item=><article className={css.entry} key={item.id}><div className={css.entryTitle}><span className={css.badge+" "+(item.type==="food"?css.food:css.move)}>{item.type==="food"?<Apple size={17}/>:<Dumbbell size={17}/>}</span><div><strong>{item.name}</strong><small>{item.duration||item.feeling||"תיעוד קצר"}{item.note?" · "+item.note:""}</small></div></div><div className={css.entryActions}><button aria-label="עריכה" onClick={()=>setEdit(item)}><Pencil size={17}/></button><button aria-label="מחיקה" onClick={()=>remove(item)}><Trash2 size={17}/></button></div></article>)}</div>)}</section></>;
}
function BaselineForm({ profile, setD }) {
  const [draft,setDraft]=useState(profile.baseline || {weight:"",height:"",steps:"",level:"",timeline:"",legPress:"",chestPress:"",row:""});
  const save=e=>{e.preventDefault();setD(data=>({...data,profile:{...data.profile,baseline:{...draft,complete:true}}}));};
  return <section className={css.card+" "+css.baseline}><p className={css.eyebrow}>שלב הכרחי לפני בניית עומסים</p><h3>אבחון נקודת פתיחה</h3><p className={css.subtle}>בלי נתוני פתיחה, אין בסיס לקבוע משקל עבודה או קצב התקדמות. ממלאים מה שיודעים; אפשר לחזור ולעדכן.</p><form className={css.form} onSubmit={save}><div className={css.row}><label>משקל גוף (ק״ג)<input className={css.field} inputMode="decimal" value={draft.weight} onChange={e=>setDraft({...draft,weight:e.target.value})} placeholder="למשל 82"/></label><label>גובה (ס״מ)<input className={css.field} inputMode="numeric" value={draft.height} onChange={e=>setDraft({...draft,height:e.target.value})} placeholder="למשל 178"/></label></div><label>צעדים ממוצעים בפועל<input className={css.field} inputMode="numeric" value={draft.steps} onChange={e=>setDraft({...draft,steps:e.target.value})} placeholder="למשל 4500"/></label><label>רמת יכולת כרגע<select className={css.field} value={draft.level} onChange={e=>setDraft({...draft,level:e.target.value})}><option value="">בחירה</option><option>לא התאמנתי בתקופה האחרונה</option><option>מתחיל/ה</option><option>חוזר/ת להתאמן</option><option>מתאמן/ת קבוע</option></select></label><label>מתי תרצה/י לבדוק התקדמות?<select className={css.field} value={draft.timeline} onChange={e=>setDraft({...draft,timeline:e.target.value})}><option value="">בחירה</option><option>בעוד 4 שבועות</option><option>בעוד 8 שבועות</option><option>בעוד 12 שבועות</option></select></label><details><summary>משקלי עבודה נוכחיים, אם ידועים</summary><p className={css.subtle}>משקל שבו הצלחת לבצע 8–12 חזרות בצורה נוחה. לא חובה, ולא מנחשים.</p><div className={css.row}><label>לחיצת רגליים<input className={css.field} inputMode="decimal" value={draft.legPress} onChange={e=>setDraft({...draft,legPress:e.target.value})} placeholder="ק״ג"/></label><label>לחיצת חזה<input className={css.field} inputMode="decimal" value={draft.chestPress} onChange={e=>setDraft({...draft,chestPress:e.target.value})} placeholder="ק״ג"/></label></div><label>חתירה<input className={css.field} inputMode="decimal" value={draft.row} onChange={e=>setDraft({...draft,row:e.target.value})} placeholder="ק״ג"/></label></details><button className={css.primary+" "+css.wide}>שמירה ובניית התוכנית</button></form></section>;
}
function ProgramCard({ profile, setD }) {
  const baseline=profile.baseline; const restricted=profile.safety && profile.safety!=="לא ידוע לי על מגבלה"; const count=Math.min(3,Math.max(1,Number(profile.availability)||2)); const gym=(Array.isArray(profile.place)?profile.place:[profile.place]).includes("חדר כושר"); const days=["A","B","C"].slice(0,count);
  if(restricted)return <section className={css.card+" "+css.programCard}><h3>התוכנית ממתינה לאיש/ת מקצוע</h3><p>סומנה מגבלה או אי־ודאות. לא יוצרים תוכנית תרגילים מותאמת עד לקבלת הכוונה מקצועית.</p></section>;
  if(!baseline?.complete)return <BaselineForm profile={profile} setD={setD} />;
  const workouts = gym ? {A:[["לחיצת רגליים",baseline.legPress],["לחיצת חזה במכונה",baseline.chestPress],["חתירה בישיבה",baseline.row],["פלאנק קצר","משקל גוף"]],B:[["דדליפט רומני עם משקולות","בחירת משקל"],["לחיצת כתפיים במכונה","בחירת משקל"],["פולי עליון","בחירת משקל"],["דד־באג","משקל גוף"]],C:[["סקוואט גביע","בחירת משקל"],["לחיצת חזה בשיפוע","בחירת משקל"],["חתירה ביד אחת","בחירת משקל"],["נשיאת משקולות","בחירת משקל"]]} : {A:[["סקוואט לכיסא","משקל גוף"],["שכיבות סמיכה על קיר","משקל גוף"],["גשר ישבן","משקל גוף"],["פלאנק קצר","משקל גוף"]],B:[["לאנג׳ אחורי נתמך","משקל גוף"],["חתירה עם גומייה / תיק","בחירת עומס"],["לחיצת כתפיים עם גומייה","בחירת עומס"],["דד־באג","משקל גוף"]],C:[["עלייה למדרגה נמוכה","משקל גוף"],["שכיבות סמיכה על שולחן","משקל גוף"],["היפ־הינג׳ עם תיק","בחירת עומס"],["Bird-dog","משקל גוף"]]};
  return <section className={css.card+" "+css.programCard}><p className={css.eyebrow}>תוכנית התחלה · בדיקה מחדש: {baseline.timeline || "בעוד 4 שבועות"}</p><h3>{count} אימונים בשבוע · {profile.sessionLength}</h3><p className={css.subtle}>ימי אימון: {Array.isArray(profile.trainingDays)?profile.trainingDays.join(" · "):"גמיש"}. בכל תרגיל נשארים 2–3 חזרות לפני מאמץ מרבי; אם אין נתון משקל, מתחילים קל ומתעדים.</p>{days.map(id=><div className={css.workoutBlock} key={id}><h4>אימון {id}</h4>{workouts[id].map(([name,load])=><p key={name}>• {name} — 2 סטים × 8–12 חזרות <em>{"· "+(load || "לתעד משקל")}</em></p>)}<small>מנוחה: 60–90 שניות בין סטים.</small></div>)}<div className={css.workoutBlock}><h4>צעדים ותנועה</h4><p>קו פתיחה: {baseline.steps || "לא הוזן"} צעדים. השבוע המטרה היא תוספת קטנה שנוחה לך, לא קפיצה חדה.</p></div><p className={css.safetyNote}>אם יש כאב חד, סחרחורת או תחושה חריגה — עוצרים ופונים לאיש/ת מקצוע.</p></section>;
}
function Plan({ d,setD }) {
 const [text,setText]=useState(""),[date,setDate]=useState(localISO()),[kind,setKind]=useState("move");const items=[...(d.plan||[])].map(x=>({...x,date:x.date||localISO()})).sort((a,b)=>a.date.localeCompare(b.date));
 const add=e=>{e.preventDefault();if(!text.trim())return;setD(p=>({...p,plan:[...p.plan,{id:uid(),text:text.trim(),date,kind,status:"planned"}]}));setText("");};
 const change=(id,status)=>setD(p=>({...p,plan:p.plan.map(x=>x.id===id?{...x,status,date:status==="tomorrow"?addDays(1):x.date}:x)}));
 return <><div className={css.sectionHead}><h2>התוכנית שלי</h2><button className={css.linkButton} onClick={()=>setD(p=>({...p,profile:{...p.profile,onboardingStep:0,complete:false}}))}>עדכון פרופיל</button></div><p className={css.subtle}>הטיוטה נבנית לפי השאלון. אפשר לשנות את הפרופיל בכל זמן.</p><ProgramCard profile={d.profile} setD={setD}/><section className={css.card+" "+css.nutritionCard}><p className={css.eyebrow}>תזונה · מסגרת פשוטה</p><h3>מה מתאים לשבוע הקרוב?</h3><p>תיעוד של ארוחות הוא הבסיס. בחר פעולה אחת: להכין ארוחה בבית, להוסיף ירק או חלבון לארוחה, או לשתות מים ליד הארוחה. אין כאן תפריט רפואי או ספירת קלוריות.</p></section><h3 className={css.sectionTitle}>פעולות שתכננת</h3><form className={css.card+" "+css.form} onSubmit={add}><label>פעולה קטנה<input className={css.field} value={text} onChange={e=>setText(e.target.value)} placeholder="למשל הליכה קצרה או להכין ארוחה בבית"/></label><div className={css.row}><label>מתי?<input className={css.field} type="date" dir="ltr" value={date} onChange={e=>setDate(e.target.value)}/></label><label>סוג<select className={css.field} value={kind} onChange={e=>setKind(e.target.value)}><option value="move">תנועה</option><option value="food">תזונה</option><option value="personal">אישי</option></select></label></div><button className={css.secondary}>הוספת פעולה</button></form><section className={css.card}>{!items.length?<Empty>אין עדיין פעולות מתוכננות. אפשר להתחיל בצעד אחד מהתוכנית למעלה.</Empty>:items.map(item=><article className={css.entry} key={item.id}><div><strong>{item.text}</strong><small>{fmt(item.date)} · {item.status==="done"?"בוצע":item.status==="skipped"?"לא השבוע":item.status==="tomorrow"?"הועבר למחר":"מתוכנן"}</small></div><div className={css.entryActions}><button className={css.status+" "+(item.status==="done"?css.done:"")} onClick={()=>change(item.id,item.status==="done"?"planned":"done")}>{item.status==="done"?<Check size={16}/>:"בוצע"}</button><button className={css.status} onClick={()=>change(item.id,"tomorrow")}>מחר</button><button className={css.status+" "+(item.status==="skipped"?css.skipped:"")} onClick={()=>change(item.id,"skipped")}>לא השבוע</button></div></article>)}</section></>;
}
function Progress({ d, setD }) {
 const days=Array.from({length:7},(_,i)=>addDays(i-6));const total=days.map(day=>d.meals.filter(x=>x.date===day).length+d.workouts.filter(x=>x.date===day&&!x.skipped).length);const logged=total.filter(Boolean).length, move=d.workouts.filter(x=>days.includes(x.date)&&!x.skipped).length, done=(d.plan||[]).filter(x=>days.includes(x.date||"")&&x.status==="done").length;
 const weekChoice = d.weekChoice || ""; const chooseWeek = value => setD(p => ({ ...p, weekChoice: value }));
 return <><div className={css.sectionHead}><h2>התמונה של השבוע</h2></div><p className={css.subtle}>אין כאן ציון. רק תמונה שתעזור להבין מה עובד עבורך.</p><div className={css.metricGrid}><div className={css.card+" "+css.metric}><span>ימים עם תיעוד</span><strong>{logged}</strong></div><div className={css.card+" "+css.metric}><span>רגעי תנועה</span><strong>{move}</strong></div></div><section className={css.card}><div className={css.barGrid}>{days.map((day,i)=><div className={css.barWrap} key={day}><i className={css.bar} style={{height:(total[i]?Math.min(100,18+total[i]*30):6)+"%"}}/><span>{new Date(day+"T12:00").toLocaleDateString("he-IL",{weekday:"narrow"})}</span></div>)}</div></section><section className={css.card}><strong>{logged?"יש לך "+logged+" ימים עם תיעוד השבוע.":"כשתתעד/י כמה ימים, יתחילו להופיע כאן דפוסים."}</strong><p className={css.subtle}>{done?"נסגרו גם "+done+" פעולות מהתוכנית.":"אפשר להשאיר את זה פשוט גם מחר."}</p></section><section className={css.card+" "+css.stack}><div><strong>מה כדאי לשמור לשבוע הבא?</strong><p className={css.subtle}>בחירה קטנה, בלי להתחייב לתוכנית חדשה.</p></div><div className={css.weekChoices}>{["פחות עומס", "יותר תיעוד", "להשאיר כמו שזה"].map(value => <button key={value} className={weekChoice === value ? css.selected : ""} onClick={() => chooseWeek(value)}>{value}</button>)}</div>{weekChoice && <p className={css.subtle}>נשמור על הכיוון: {weekChoice}.</p>}</section></>;
}
function SettingsView({ d,setD,editProfile }) {const [confirm,setConfirm]=useState(false);const exp=()=>{const blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="personal-hq-health.json";a.click();URL.revokeObjectURL(a.href)};return <div className={css.stack}><section className={css.card}><h2>הפרופיל והתוכנית שלי</h2><p className={css.subtle}>אפשר לעדכן מטרות, מקום אימון, ימים, שעות וזמן אימון. התוכנית נבנית מחדש לפי הבחירות.</p><button className={css.secondary} onClick={editProfile}>עדכון פרופיל האימונים</button></section><section className={css.card}><h2>פרטיות ומידע</h2><p className={css.subtle}>המידע נשמר בחשבון המאובטח שלך. מידע על מגבלות אינו משמש להצעה אוטומטית.</p><button className={css.secondary} onClick={exp}>ייצוא הנתונים</button></section><section className={css.card}><h2>גבולות המערכת</h2><p className={css.subtle}>כלי לתיעוד והרגלים, לא תחליף לייעוץ רפואי או תזונתי. אם משהו כואב, מחמיר או מרגיש חריג — עוצרים ופונים לאיש מקצוע.</p></section><section className={css.card}><h2>מחיקת הנתונים</h2><p className={css.subtle}>הפעולה מוחקת את כל נתוני חברת האימון והתזונה.</p><button className={css.status+" "+css.skipped} onClick={()=>confirm?(setD(INIT),setConfirm(false)):setConfirm(true)}>{confirm?"לחיצה נוספת למחיקה":"מחיקת כל הנתונים"}</button></section></div>}

export default function HealthApp() {
 const {data:d,setData:setD,ready}=useStore(STORE_KEY,INIT);const [tab,setTab]=useState("today"),[composer,setComposer]=useState(null),[more,setMore]=useState(false),[deleted,setDeleted]=useState(null),[toast,setToast]=useState("");
 const navigate = nextTab => { setComposer(null); setMore(false); setTab(nextTab); };
 const editProfile = () => setD(data => ({ ...data, profile:{ ...data.profile, onboardingStep:0, complete:false } }));
 const notify=(message)=>{setComposer(null);setToast(message+" יפה שפינית לזה רגע.");setTimeout(()=>setToast(""),5000)};
 const remove=item=>{setD(p=>item.type==="food"?{...p,meals:p.meals.filter(x=>x.id!==item.id)}:{...p,workouts:p.workouts.filter(x=>x.id!==item.id)});setDeleted(item);setToast("הפריט נמחק.");setTimeout(()=>setDeleted(null),7000)};
 const undo=()=>{if(!deleted)return;setD(p=>deleted.type==="food"?{...p,meals:[deleted,...p.meals]}:{...p,workouts:[deleted,...p.workouts]});setDeleted(null);setToast("הפריט הוחזר.");};
 if(!ready)return <div className={css.empty}>טוען את היומן…</div>;
 if(!d.profile.complete)return <div className={css.shell}><Onboarding d={d} setD={setD}/></div>;
 const content=composer?<Composer kind={composer} onClose={()=>setComposer(null)} d={d} setD={setD} onSaved={notify}/>:tab==="today"?<Today d={d} setD={setD} setTab={setTab} setComposer={setComposer}/>:tab==="journal"?<Journal d={d} setD={setD} setComposer={setComposer} remove={remove}/>:tab==="plan"?<Plan d={d} setD={setD}/>:tab==="progress"?<Progress d={d} setD={setD}/>:<SettingsView d={d} setD={setD} editProfile={editProfile}/>;
 return <div className={css.shell}><Header setTab={navigate}/><Nav tab={tab} onNavigate={navigate}/><main className={css.content}>{content}</main>{toast&&<div className={css.toast} role="status"><span>{toast}</span>{deleted&&<button onClick={undo}>ביטול</button>}</div>}</div>;
}
