"use client";
import { useState } from "react";
import Link from "next/link";
import { Check, ChevronLeft, Plus, Trash2, CalendarDays } from "lucide-react";
import { useStore } from "@/lib/store";
import { INIT, STORE_KEY, normalize, uid } from "../model";
import css from "./wellbeing-v6.module.css";

const TABS=[["inbox","Inbox"],["today","היום"],["week","השבוע"]];
const labels={inbox:"לא חשוב כרגע",today:"היום",tomorrow:"מחר",week:"השבוע",later:"בהמשך"};
const tomorrowISO=()=>{const d=new Date();d.setDate(d.getDate()+1);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const displayDate=(value)=>{const date=new Date(value+"T12:00");return Number.isNaN(date.getTime())?"":date.toLocaleDateString("he-IL",{day:"numeric",month:"short"})};
export default function OriaDailyCommand(){
 const {data,setData,ready}=useStore(STORE_KEY,INIT);
 const [tab,setTab]=useState("inbox"),[title,setTitle]=useState(""),[bucket,setBucket]=useState("inbox"),[review,setReview]=useState("");
 const d=normalize(data),tasks=Array.isArray(d.tasks)?d.tasks:[],today=tasks.filter(x=>x.bucket==="today"),inbox=tasks.filter(x=>x.bucket==="inbox"),week=tasks.filter(x=>x.bucket==="week"||x.bucket==="tomorrow");
 const saveTasks=(fn)=>setData(prev=>({...normalize(prev),tasks:fn(normalize(prev).tasks||[])}));
 const add=()=>{if(!title.trim())return;saveTasks(xs=>[{id:uid(),title:title.trim(),bucket,due,done:false,createdAt:new Date().toISOString()},...xs]);setTitle("");};
 const move=(task,b)=>{if(b==="today"&&task.bucket!=="today"&&today.filter(x=>!x.done).length>=3){window.alert("כדי לשמור על יום אפשרי, בחר עד 3 פעולות פתוחות להיום.");return;}saveTasks(xs=>xs.map(x=>x.id===task.id?{...x,bucket:b}:x));};
 const remove=(id)=>{if(!window.confirm("למחוק את הפעולה?"))return;saveTasks(xs=>xs.filter(x=>x.id!==id));};
 const item=(task)=><article className={css.task} key={task.id}><button className={task.done?css.done:css.check} onClick={()=>saveTasks(xs=>xs.map(x=>x.id===task.id?{...x,done:!x.done}:x))} aria-label="סימון ביצוע">{task.done&&<Check size={15}/>}</button><div className={css.taskText}><strong className={task.done?css.struck:""}>{task.title}</strong><div className={css.meta}>{displayDate(task.due)&&<span><CalendarDays size={14}/>{displayDate(task.due)}</span>}<select value={task.bucket||"inbox"} onChange={e=>move(task,e.target.value)}>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div></div><button className={css.delete} onClick={()=>remove(task.id)} aria-label="מחיקה"><Trash2 size={17}/></button></article>;
 if(!ready)return <main className={css.loading}>טוען…</main>;
 return <main className={css.shell} dir="rtl"><header><Link href="/" className={css.back}><ChevronLeft size={17}/>חזרה למנכ״ל</Link><p>היד הימנית שלך</p><h1>אוריה · סדר החיים</h1></header>
 <nav className={css.tabs}>{TABS.map(([id,label])=><button key={id} className={tab===id?css.active:""} onClick={()=>setTab(id)}>{label}{id==="today"&&<small>{today.filter(x=>!x.done).length}/3</small>}</button>)}</nav>
 {tab==="inbox"&&<section className={css.stack}><div className={css.hero}><p>לזרוק מהראש</p><h2>מה צריך לזכור או לטפל בו?</h2><span>כתוב ואז בחר: היום, מחר, או לא חשוב כרגע.</span></div><article className={css.card}><textarea className={css.field} value={title} onChange={e=>setTitle(e.target.value)} placeholder="למשל: לתאם עם המוביל, לבדוק מסלול משכנתא, לקבוע תור…" /><div className={css.addRow}><div className={css.quickChoices} aria-label="מתי לטפל"><button className={bucket==="today"?css.chosen:""} onClick={()=>setBucket("today")}>היום</button><button className={bucket==="tomorrow"?css.chosen:""} onClick={()=>setBucket("tomorrow")}>מחר</button><button className={bucket==="inbox"?css.chosen:""} onClick={()=>setBucket("inbox")}>לא חשוב כרגע</button></div><button className={css.primary} onClick={add}><Plus size={18}/>הוספה</button></div></article><article className={css.card}><div className={css.head}><h2>ממתין למיון</h2><span>{inbox.length}</span></div>{!inbox.length?<p className={css.empty}>ריק — זה מצוין.</p>:inbox.map(item)}</article></section>}
 {tab==="today"&&<section className={css.stack}><div className={css.hero}><p>רק מה שאפשר היום</p><h2>שלוש הפעולות החשובות שלך.</h2><span>בחר עד שלוש. כל השאר יכול לחכות, והוא לא הולך לאיבוד.</span></div><article className={css.card}><div className={css.head}><h2>היום</h2><span>{today.filter(x=>!x.done).length}/3 פתוחות</span></div>{!today.length?<p className={css.empty}>העבר לכאן עד שלוש פעולות מה־Inbox או מהשבוע.</p>:today.map(item)}</article><article className={css.card}><h2>תיאום עם יומן המשפחה</h2><p className={css.empty}>משימה עם תאריך היא מועמדת לתיאום. כתוב לי כאן בצ׳אט מה צריך להיכנס ליומן; אני אבדוק זמינות ביומן המשפחה ואבקש את אישורך לפני יצירה.</p></article></section>}
 {tab==="week"&&<section className={css.stack}><div className={css.hero+" "+css.light}><p>מבט קדימה</p><h2>מה צריך לקבל מקום השבוע?</h2><span>מעבירים לכאן דברים חשובים, בלי להפוך אותם לדחופים בכוח.</span></div><article className={css.card}><div className={css.head}><h2>מחר והשבוע</h2><span>{week.filter(x=>!x.done).length} פתוחות</span></div>{!week.length?<p className={css.empty}>אין פעולות לשבוע כרגע.</p>:week.map(item)}</article><article className={css.card}><h2>סקירת שבוע קצרה</h2><textarea className={css.field} value={review||d.weekReview||""} onChange={e=>setReview(e.target.value)} placeholder="מה התקדם, מה נתקע, ומה חייב לעבור לשבוע הבא?" /><button className={css.primary} onClick={()=>setData(prev=>({...normalize(prev),weekReview:review}))}>שמירת סקירה</button></article></section>}
 </main>;
}