"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, ChevronLeft, Clock3, ExternalLink, Pause, Play, Plus, Radar, RotateCcw, Square, Trash2 } from "lucide-react";
import { useStore } from "@/lib/store";
import { INIT, STORE_KEY, normalize, uid } from "../model";
import css from "./wellbeing-v6.module.css";

const tomorrowISO=()=>{const d=new Date();d.setDate(d.getDate()+1);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const dayAfterISO=()=>{const d=new Date();d.setDate(d.getDate()+2);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const TABS=[["today","היום"],["tomorrow","מחר"],["next48","48 שעות"],["follow","מעקב"]];
const PRIORITIES=[["urgent","דחוף"],["high","גבוה"],["normal","רגיל"],["low","נמוך"]];
const priorityLabel=(value)=>PRIORITIES.find(([key])=>key===value)?.[1]||"רגיל";
const priorityRank=(value)=>({urgent:0,high:1,normal:2,low:3})[value]??2;
const ordered=(list)=>[...list].sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||(a.due||"9999").localeCompare(b.due||"9999"));
const owner=(task)=>task.owner||"לירון";
const source=(task)=>task.source||"אוריה";
const taskLink=(task)=>/^https?:\/\//i.test(task?.link?.trim()||"") ? task.link.trim() : "";
const two=(number)=>String(Math.max(0,number)).padStart(2,"0");

export default function OriaControlRoom(){
 const {data,setData,ready}=useStore(STORE_KEY,INIT);
 const [tab,setTab]=useState("today"),[title,setTitle]=useState(""),[link,setLink]=useState(""),[priority,setPriority]=useState("normal"),[slot,setSlot]=useState("today"),[notice,setNotice]=useState("");
 const [focusTask,setFocusTask]=useState(null),[focusMinutes,setFocusMinutes]=useState(25),[breakMinutes,setBreakMinutes]=useState(5),[timerMode,setTimerMode]=useState("focus"),[secondsLeft,setSecondsLeft]=useState(1500),[running,setRunning]=useState(false),[rounds,setRounds]=useState(0),[targetRounds,setTargetRounds]=useState(1),[quickOpen,setQuickOpen]=useState(false),[hydrated,setHydrated]=useState(false);
 const state=normalize(data),tasks=Array.isArray(state.tasks)?state.tasks:[],waiting=Array.isArray(state.waiting)?state.waiting:[],decisions=Array.isArray(state.decisionLog)?state.decisionLog:[];
 const today=ordered(tasks.filter(x=>x.bucket==="today"&&!x.done)),tomorrow=ordered(tasks.filter(x=>x.bucket==="tomorrow"&&!x.done)),dayAfter=ordered(tasks.filter(x=>x.bucket==="week"&&!x.done)),next48=ordered([...tomorrow,...dayAfter]);
 const proposal=today.slice(0,3),now=today[0]||tomorrow[0]||null,overload=today.length>5;
 const duplicateDates=Object.values([...today,...tomorrow,...dayAfter].filter(x=>x.due).reduce((acc,x)=>({...acc,[x.due]:(acc[x.due]||0)+1}),{})).some(count=>count>1);
 const tell=(text)=>{setNotice(text);window.setTimeout(()=>setNotice(""),2800)};
 const mutate=(fn)=>setData(prev=>({...normalize(prev),tasks:fn(normalize(prev).tasks||[])}));
 const saveTimer=(patch)=>setData(prev=>({...normalize(prev),focusTimer:{...(normalize(prev).focusTimer||{}),...patch}}));
 useEffect(()=>{if(!ready||hydrated)return;const saved=state.focusTimer||{};const fm=[15,25,45,60].includes(saved.focusMinutes)?saved.focusMinutes:25;const bm=[5,10,15].includes(saved.breakMinutes)?saved.breakMinutes:5;setFocusMinutes(fm);setBreakMinutes(bm);setTimerMode(saved.mode==="break"?"break":"focus");setSecondsLeft(Number.isFinite(saved.secondsLeft)&&saved.secondsLeft>0?saved.secondsLeft:fm*60);setRounds(Number.isFinite(saved.rounds)?saved.rounds:0);setFocusTask(saved.task||null);setTargetRounds(Number.isInteger(saved.targetRounds)?saved.targetRounds:1);setHydrated(true)},[ready,hydrated,state.focusTimer]);
 useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setSecondsLeft(left=>{if(left>1)return left-1;const completed=timerMode==="focus",nextMode=completed?"break":"focus",nextSeconds=(completed?breakMinutes:focusMinutes)*60;setTimerMode(nextMode);setRunning(false);if(completed)setRounds(value=>value+1);saveTimer({mode:nextMode,secondsLeft:nextSeconds,running:false,rounds:rounds+(completed?1:0),targetRounds,focusMinutes,breakMinutes,task:focusTask});tell(completed?(rounds+1>=targetRounds?"כל הפעימות הושלמו. אפשר לסמן את המשימה כבוצעה כשאתה מוכן.":"פעימה "+(rounds+1)+" מתוך "+targetRounds+" הושלמה. אפשר לקחת הפסקה קצרה."):"ההפסקה הסתיימה. כשתהיה מוכן אפשר להתחיל את הפעימה הבאה.");return nextSeconds}),1000);return()=>window.clearInterval(timer)},[running,timerMode,focusMinutes,breakMinutes,rounds,targetRounds,focusTask]);
 useEffect(()=>{if(!running||secondsLeft%15!==0)return;saveTimer({task:focusTask,mode:timerMode,secondsLeft,running:true,focusMinutes,breakMinutes,rounds,targetRounds})},[secondsLeft,running,timerMode,focusMinutes,breakMinutes,rounds,targetRounds,focusTask]);
 const add=()=>{if(!title.trim())return;const bucket=slot==="tomorrow"?"tomorrow":slot==="dayAfter"?"week":slot==="later"?"inbox":"today";const due=slot==="tomorrow"?tomorrowISO():slot==="dayAfter"?dayAfterISO():"";mutate(xs=>[{id:uid(),title:title.trim(),bucket,due,source:"אוריה",owner:"לירון",link:taskLink({link}),priority,pomodoros:1,done:false},...xs]);setTitle("");setLink("");setPriority("normal");tell("הפעולה נוספה.");};
 const done=(id)=>mutate(xs=>xs.map(x=>x.id===id?{...x,done:!x.done}:x));
 const remove=(id)=>{if(!window.confirm("למחוק את הפעולה?"))return;mutate(xs=>xs.filter(x=>x.id!==id));tell("הפעולה הוסרה.");};
 const changePriority=(id,value)=>mutate(xs=>xs.map(x=>x.id===id?{...x,priority:value}:x));
 const changePomodoros=(id,value)=>mutate(xs=>xs.map(x=>x.id===id?{...x,pomodoros:Number(value)}:x));
 const approveMorning=()=>{setData(prev=>({...normalize(prev),morningPlan:{approvedAt:new Date().toISOString(),taskIds:proposal.map(task=>task.id)}}));tell("סדר היום אושר. לא בוצע שינוי במשימות עצמן.");};
 const beginFocus=(task)=>{const selected={id:task.id,title:task.title};const total=task.pomodoros||1;setFocusTask(selected);setTargetRounds(total);setRounds(0);setTimerMode("focus");setSecondsLeft(focusMinutes*60);setRunning(true);setQuickOpen(true);saveTimer({task:selected,mode:"focus",secondsLeft:focusMinutes*60,running:true,focusMinutes,breakMinutes,rounds:0,targetRounds:total});tell("פעימה 1 מתוך "+total+" התחילה.");};
 const pauseFocus=()=>{setRunning(false);saveTimer({task:focusTask,mode:timerMode,secondsLeft,running:false,focusMinutes,breakMinutes,rounds,targetRounds});};
 const stopFocus=()=>{setRunning(false);setTimerMode("focus");setSecondsLeft(focusMinutes*60);saveTimer({task:focusTask,mode:"focus",secondsLeft:focusMinutes*60,running:false,focusMinutes,breakMinutes,rounds,targetRounds});};
 const row=(task)=><article key={task.id} className={css.commandRow}><button className={css.check} onClick={()=>done(task.id)} aria-label="סמן שבוצע"><Check size={15}/></button><div className={css.rowMain}><div className={css.taskTitle}><strong>{task.title}</strong><span className={css.priorityBadge+" "+css["priority_"+(task.priority||"normal")]}>{priorityLabel(task.priority)}</span></div><span><i>{source(task)}</i> · בעלים: {owner(task)}</span><div className={css.taskControls}><label>עדיפות<select aria-label={"עדיפות עבור "+task.title} value={task.priority||"normal"} onChange={e=>changePriority(task.id,e.target.value)}>{PRIORITIES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>פעימות<select aria-label={"מספר פעימות עבור "+task.title} value={task.pomodoros||1} onChange={e=>changePomodoros(task.id,e.target.value)}>{[1,2,3,4,5,6,7,8].map(value=><option key={value} value={value}>{value}×{focusMinutes} דק׳</option>)}</select></label><button className={css.focusLink} onClick={()=>beginFocus(task)}><Play size={13}/>פוקוס</button>{taskLink(task)?<a className={css.taskLink} href={taskLink(task)} target="_blank" rel="noreferrer"><ExternalLink size={14}/>פתיחת קישור</a>:<span className={css.noLink}>אין קישור</span>}</div></div><button className={css.delete} onClick={()=>remove(task.id)} aria-label="מחיקה"><Trash2 size={17}/></button></article>;
 const sortedWaiting=useMemo(()=>waiting.filter(x=>!x.done),[waiting]);
 if(!ready)return <main className={css.loading}>טוען את מרכז השליטה…</main>;
 return <main className={css.shell} dir="rtl"><header className={css.commandHeader}><Link href="/" className={css.back}><ChevronLeft size={17}/>חזרה למנכ״ל</Link><div><p>ORIA / DAILY COMMAND</p><h1>מרכז השליטה האישי</h1></div><span className={css.orbit} aria-hidden="true"><Radar size={22}/></span></header>
 {notice&&<div className={css.toast} role="status" aria-live="polite">{notice}</div>}
 <nav className={css.tabs}>{TABS.map(([id,label])=><button key={id} className={tab===id?css.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="today"&&<section className={css.stack}><section className={css.nowCard}><p>הפעולה הבאה</p>{now?<><h2>{now.title}</h2><span>מקור: {source(now)} · בעלים: {owner(now)}</span>{taskLink(now)&&<a className={css.nowLink} href={taskLink(now)} target="_blank" rel="noreferrer"><ExternalLink size={15}/>פתיחת קישור</a>}<button onClick={()=>done(now.id)}><Check size={17}/>סימון בוצע</button></>:<><h2>אין פעולה בוערת כרגע.</h2><span>זה זמן טוב להכניס דבר אחד שחשוב לך.</span></>}</section>
 <article className={css.card}><div className={css.head}><div><h2>הצעת בוקר מאוריה</h2><p className={css.hint}>שלוש פעולות שמגיעות ראשונות לפי עדיפות. אפשר לאשר את הסדר — בלי שהמערכת תשנה עבורך שום דבר.</p></div><button className={css.approve} onClick={approveMorning} disabled={!proposal.length}>אישור סדר היום</button></div>{!proposal.length?<p className={css.empty}>אין עדיין פעולות להיום כדי להציע סדר.</p>:<ol className={css.proposal}>{proposal.map(task=><li key={task.id}><b>{task.title}</b><span>{priorityLabel(task.priority)} · {source(task)}</span></li>)}</ol>}</article>
 <article className={css.card}><div className={css.head}><h2>הכנסה מהירה</h2><span>בלי תאריך ידני</span></div><textarea className={css.field} value={title} onChange={e=>setTitle(e.target.value)} placeholder="מה צריך לטפל בו?" /><input className={css.linkField} type="url" dir="ltr" value={link} onChange={e=>setLink(e.target.value)} placeholder="https:// קישור רלוונטי (לא חובה)" /><div className={css.quickChoices}><button className={slot==="today"?css.chosen:""} onClick={()=>setSlot("today")}>היום</button><button className={slot==="tomorrow"?css.chosen:""} onClick={()=>setSlot("tomorrow")}>מחר</button><button className={slot==="dayAfter"?css.chosen:""} onClick={()=>setSlot("dayAfter")}>מחרתיים</button><button className={slot==="later"?css.chosen:""} onClick={()=>setSlot("later")}>לא חשוב כרגע</button><select aria-label="עדיפות למשימה חדשה" value={priority} onChange={e=>setPriority(e.target.value)}>{PRIORITIES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button className={css.primary} onClick={add}><Plus size={18}/>הוספה</button></div></article>
 <article className={css.card}><div className={css.head}><div><h2>כל המשימות להיום</h2><p className={css.hint}>ממוינות לפי עדיפות ואז לפי תאריך. כולן מוצגות — בלי מגבלת כמות.</p></div><span>{today.length} משימות</span></div>{!today.length?<p className={css.empty}>בחר פעולה אחת. לא צריך לתכנן את כל החיים היום.</p>:today.map(row)}</article>
 {(overload||duplicateDates)&&<article className={css.reliefCard}><Clock3 size={20}/><div><strong>{overload?"היום עמוס":"בדיקת תיאום"}</strong><p>{overload?("יש "+today.length+" משימות להיום. ההצעה היא לאשר את שלוש הפעולות העליונות ולהשאיר את השאר גלויות — בלי למחוק או להזיז אוטומטית."):"יש כמה פעולות באותו תאריך. כדאי לוודא שהן לא מתנגשות לפני שמאשרים את סדר היום."}</p></div></article>}
 <article className={css.focusCard}><div><p>פוקוס</p><h2>{focusTask?.title||"בחר משימה והתחל סבב"}</h2><span>{timerMode==="focus"?"זמן עבודה":"הפסקה"} · {Math.floor(secondsLeft/60)}:{two(secondsLeft%60)} · פעימה {Math.min(rounds+1,targetRounds)}/{targetRounds}</span></div><div className={css.timerSettings}><label>עבודה<select value={focusMinutes} onChange={e=>{const value=Number(e.target.value);setFocusMinutes(value);if(!running&&timerMode==="focus")setSecondsLeft(value*60)}}>{[15,25,45,60].map(x=><option key={x} value={x}>{x} דק׳</option>)}</select></label><label>הפסקה<select value={breakMinutes} onChange={e=>setBreakMinutes(Number(e.target.value))}>{[5,10,15].map(x=><option key={x} value={x}>{x} דק׳</option>)}</select></label></div><div className={css.timerActions}>{!running?<button className={css.primary} disabled={!focusTask} onClick={()=>setRunning(true)}><Play size={16}/>התחל</button>:<button className={css.secondary} onClick={pauseFocus}><Pause size={16}/>השהיה</button>}<button className={css.secondary} disabled={!focusTask} onClick={stopFocus}><Square size={15}/>עצור</button><button className={css.secondary} disabled={!focusTask} onClick={()=>{setTimerMode("focus");setSecondsLeft(focusMinutes*60);setRounds(0)}}><RotateCcw size={16}/>איפוס</button></div></article></section>}
 {focusTask&&<aside className={css.floatingTimer} aria-label="בקרת פוקוס פעילה"><button className={css.floatingChip} onClick={()=>setQuickOpen(value=>!value)} aria-expanded={quickOpen}><Clock3 size={17}/><span>{Math.floor(secondsLeft/60)}:{two(secondsLeft%60)}</span><b>{focusTask.title}</b></button>{quickOpen&&<div className={css.quickPanel}><strong>פעימה {Math.min(rounds+1,targetRounds)}/{targetRounds} · {timerMode==="focus"?"עבודה":"הפסקה"}</strong><div>{!running?<button onClick={()=>setRunning(true)}><Play size={14}/>המשך</button>:<button onClick={pauseFocus}><Pause size={14}/>השהיה</button>}<button onClick={stopFocus}><RotateCcw size={14}/>איפוס</button></div></div>}</aside>}\n {tab==="tomorrow"&&<section className={css.stack}><section className={css.hero+" "+css.light}><p>מחר</p><h2>{new Date(tomorrowISO()+"T12:00").toLocaleDateString("he-IL",{weekday:"long",day:"numeric",month:"long"})}</h2><span>תצוגה נפרדת כדי להכין את מחר בלי לערבב אותו עם היום.</span></section><article className={css.card}>{!tomorrow.length?<p className={css.empty}>אין פעולות מתוכננות למחר.</p>:tomorrow.map(row)}</article></section>}
 {tab==="next48"&&<section className={css.stack}><section className={css.hero+" "+css.light}><p>48 השעות הקרובות</p><h2>מחר ומחרתיים</h2><span>רק מה שמתקרב, ממויין לפי עדיפות.</span></section><article className={css.card}><h2>כל הפעולות הקרובות</h2>{!next48.length?<p className={css.empty}>אין פעולות מתוכננות ל־48 השעות הקרובות.</p>:next48.map(row)}</article></section>}
 {tab==="follow"&&<section className={css.stack}><section className={css.hero+" "+css.light}><p>בלי לזכור לבד</p><h2>מה ממתין?</h2><span>דברים אצל אחרים והחלטות פתוחות נשארים כאן עד שסוגרים אותם.</span></section><article className={css.card}><h2>ממתין לבעלים</h2>{!sortedWaiting.length?<p className={css.empty}>אין כרגע מעקבים פתוחים.</p>:sortedWaiting.map(x=><div className={css.commandRow} key={x.id}><span className={css.waitDot}/><div className={css.rowMain}><strong>{x.title}</strong><span>בעלים: {x.owner||"לא הוגדר"}</span></div></div>)}</article><article className={css.card}><h2>החלטות פתוחות</h2>{!decisions.filter(x=>!x.done).length?<p className={css.empty}>אין החלטות פתוחות כרגע.</p>:decisions.filter(x=>!x.done).map(x=><div className={css.commandRow} key={x.id}><span className={css.waitDot}/><div className={css.rowMain}><strong>{x.title}</strong><span>בעלים: לירון</span></div></div>)}</article></section>}
 </main>;
}