"use client";
import { useMemo, useState } from "react";
import { Plus, Trash2, ExternalLink, AlertTriangle, Upload, X } from "lucide-react";
import { useStore, cp } from "@/lib/store";
import { STORE_KEY, INIT } from "./model";

const NAV = [
  ["dash", "חדר מצב"], ["plan", "תוכנית וזמן"], ["items", "תקציב ורכש"],
  ["suppliers", "ספקים"], ["docs", "מסמכים ובדק"],
];
const rooms = ["כניסה", "סלון", "מטבח", "פינת אוכל", "מרפסת", "חדר הורים", "חדר ילדים", "חדר עבודה", "חדר רחצה", "שירותי אורחים", "כביסה / מחסן", "מערכות"];
const categories = ["מיזוג", "חשמל ותאורה", "נגרות", "ריהוט", "פרקט וריצוף", "מוצרי חשמל", "צביעה וגמרים", "תקשורת", "אחר"];

const money = n => new Intl.NumberFormat("he-IL", { style: "currency", currency: "ILS", maximumFractionDigits: 0 }).format(Number(n || 0));
const emptyItem = () => ({ id: crypto.randomUUID(), name: "", room: rooms[0], category: categories[0], supplierId: "", supplierName: "", estimate: 0, finalCost: 0, status: "לבחירה", dueDate: "", reminderDaysBefore: "", reminderNote: "", reminderDone: false, link: "", note: "", payments: [], files: [], beforeMove: true, updatedAt: new Date().toISOString() });
const emptySupplier = () => ({ id: crypto.randomUUID(), name: "", trade: "", phone: "", note: "" });
function ensure(data) {
  if (data?.renovationV2) return data;
  const legacy = data?.reno || [];
  return { renovationV2: true, items: legacy.map(x => ({ ...emptyItem(), id: String(x.id), name: x.n || "", category: x.cat || "אחר", estimate: x.est || 0, finalCost: x.act || 0, note: x.note || "", link: x.link || "", payments: x.advance ? [{ id: crypto.randomUUID(), amount: x.advance, date: "", note: "מקדמה שהועברה מהמערכת הקודמת" }] : [], status: x.done ? "הושלם" : "לבחירה" })), suppliers: [], milestones: [{ id: "handover", name: "קבלת מפתח", date: "", status: "דורש אימות", blocker: "יש לאמת שנה ומועד" }, { id: "move", name: "כניסה לדירה", date: "", status: "דורש אימות", blocker: "יש לאמת שנה ומועד" }], documents: [] };
}
function setState(setData, updater) { setData(prev => ({ ...prev, ...updater(ensure(cp(prev))) })); }
function Btn({ children, onClick, secondary, disabled }) { return <button disabled={disabled} onClick={onClick} style={{ minHeight: 44, border: secondary ? "1px solid #DCE3DE" : "none", borderRadius: 10, padding: "0 14px", background: secondary ? "#fff" : "#256B57", color: secondary ? "#18231E" : "#fff", font: "inherit", cursor: disabled ? "not-allowed" : "pointer", display: "inline-flex", alignItems: "center", gap: 7 }}>{children}</button>; }
function Card({ children, style }) { return <section style={{ background: "#fff", border: "1px solid #DCE3DE", borderRadius: 14, padding: 16, ...style }}>{children}</section>; }
function Field({ label, children }) { return <label style={{ display: "grid", gap: 5, fontSize: 14, color: "#44514A" }}><span>{label}</span>{children}</label>; }
const input = { minHeight: 44, width: "100%", border: "1px solid #C9D3CC", borderRadius: 9, padding: "0 10px", background: "#fff", font: "inherit", fontSize: 16, color: "#18231E" };
function ItemEditor({ item, suppliers, onSave, onClose }) {
  const [draft, setDraft] = useState(item || emptyItem());
  const paid = draft.payments.reduce((s, p) => s + Number(p.amount || 0), 0);
  const total = Number(draft.finalCost || draft.estimate || 0);
  const patch = (key, value) => setDraft(d => ({ ...d, [key]: value }));
  const pay = () => setDraft(d => ({ ...d, payments: [...d.payments, { id: crypto.randomUUID(), amount: 0, date: "", note: "" }] }));
  return <Card style={{ position: "fixed", inset: 12, zIndex: 20, overflow: "auto", maxWidth: 680, margin: "auto", height: "fit-content", maxHeight: "calc(100vh - 24px)", boxShadow: "0 20px 70px #18231e40" }}>
    <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><h2 style={{ margin: 0, fontSize: 21 }}>{item ? "עריכת פריט" : "רכישה חדשה"}</h2><button aria-label="סגירה" onClick={onClose} style={{ border: 0, background: "transparent" }}><X /></button></div>
    <div style={{ display: "grid", gap: 12 }}>
      <Field label="שם הפריט"><input value={draft.name} onChange={e => patch("name", e.target.value)} style={input} /></Field>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Field label="חדר / אזור"><select value={draft.room} onChange={e => patch("room", e.target.value)} style={input}>{rooms.map(x => <option key={x}>{x}</option>)}</select></Field><Field label="קטגוריה"><select value={draft.category} onChange={e => patch("category", e.target.value)} style={input}>{categories.map(x => <option key={x}>{x}</option>)}</select></Field></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Field label="עלות משוערת"><input dir="ltr" inputMode="numeric" value={draft.estimate} onChange={e => patch("estimate", Number(e.target.value))} style={input} /></Field><Field label="עלות סופית"><input dir="ltr" inputMode="numeric" value={draft.finalCost} onChange={e => patch("finalCost", Number(e.target.value))} style={input} /></Field></div>
      <Field label="ספק"><select value={draft.supplierName ? "__custom__" : draft.supplierId} onChange={e => { const value = e.target.value; if (value === "__custom__") setDraft(d => ({ ...d, supplierId: "", supplierName: "" })); else setDraft(d => ({ ...d, supplierId: value, supplierName: "" })); }} style={input}><option value="">טרם נבחר</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}<option value="__custom__">ספק אחר — הזנה חופשית</option></select></Field>
      {draft.supplierName !== undefined && (draft.supplierName || (!draft.supplierId && draft.supplierName === "")) && <Field label="שם ספק אחר"><input value={draft.supplierName} onChange={e => patch("supplierName", e.target.value)} placeholder="לדוגמה: אבי מיזוג" style={input} /></Field>}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Field label="מצב"><select value={draft.status} onChange={e => patch("status", e.target.value)} style={input}>{["לבחירה","בהצעת מחיר","הוזמן","בהמתנה לאספקה","בהתקנה","הושלם","מעוכב"].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="יעד"><input type="date" value={draft.dueDate} onChange={e => patch("dueDate", e.target.value)} style={input} /></Field></div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><Field label="תזכורת לפני היעד"><select value={draft.reminderDaysBefore ?? ""} onChange={e => patch("reminderDaysBefore", e.target.value)} style={input}><option value="">ללא תזכורת</option><option value="7">שבוע לפני</option><option value="14">שבועיים לפני</option><option value="21">3 שבועות לפני</option><option value="30">חודש לפני</option></select></Field>{draft.reminderDaysBefore ? <Field label="מה להזכיר?"><input value={draft.reminderNote || ""} onChange={e => patch("reminderNote", e.target.value)} placeholder="לדוגמה: לתאם התקנה" style={input} /></Field> : <div />}</div>
      <Field label="קישור"><input dir="ltr" value={draft.link} onChange={e => patch("link", e.target.value)} style={input} /></Field>
      <Field label="הערה"><textarea value={draft.note} onChange={e => patch("note", e.target.value)} style={{ ...input, minHeight: 76, paddingTop: 8 }} /></Field>
      <label style={{ display: "flex", gap: 8, alignItems: "center" }}><input type="checkbox" checked={draft.beforeMove} onChange={e => patch("beforeMove", e.target.checked)} /> חובה לפני כניסה</label>
      <div><strong>תשלומי ספק</strong><span style={{ color: "#63716A", marginInlineStart: 8 }}>שולם {money(paid)} · יתרה {money(Math.max(0, total - paid))}</span>{draft.payments.map((p, i) => <div key={p.id} style={{ display: "grid", gridTemplateColumns: "1fr 1fr 32px", gap: 8, marginTop: 8 }}><input dir="ltr" inputMode="numeric" value={p.amount} onChange={e => setDraft(d => ({ ...d, payments: d.payments.map((q, j) => j === i ? { ...q, amount: Number(e.target.value) } : q) }))} style={input} /><input type="date" value={p.date} onChange={e => setDraft(d => ({ ...d, payments: d.payments.map((q, j) => j === i ? { ...q, date: e.target.value } : q) }))} style={input} /><button onClick={() => setDraft(d => ({ ...d, payments: d.payments.filter((_, j) => j !== i) }))} style={{ border: 0, background: "transparent", color: "#B53A31" }}><Trash2 size={18} /></button></div>)}<button onClick={pay} style={{ border: 0, background: "transparent", color: "#256B57", font: "inherit", padding: "10px 0" }}>+ רישום תשלום</button></div>
      <div style={{ display: "flex", justifyContent: "end", gap: 8 }}><Btn secondary onClick={onClose}>ביטול</Btn><Btn onClick={() => { if (draft.name.trim()) onSave({ ...draft, updatedAt: new Date().toISOString() }); }}>שמירת פריט</Btn></div>
    </div>
  </Card>;
}
function Dashboard({ data, select }) {
  const items = data.items || []; const paid = items.reduce((s, i) => s + i.payments.reduce((a, p) => a + Number(p.amount || 0), 0), 0); const plan = items.reduce((s, i) => s + Number(i.finalCost || i.estimate || 0), 0); const urgent = items.filter(i => i.beforeMove && i.status !== "הושלם");
  const reminders = items.filter(i => i.reminderDaysBefore && i.dueDate && !i.reminderDone).map(i => { const date = new Date(`${i.dueDate}T12:00:00`); date.setDate(date.getDate() - Number(i.reminderDaysBefore)); return { item: i, date }; }).sort((a,b) => a.date - b.date);
  return <div style={{ display: "grid", gap: 14 }}><div><p style={{ color: "#63716A", margin: "0 0 4px" }}>חברת שיפוץ הבית</p><h2 style={{ margin: 0, fontSize: 26 }}>מה דורש החלטה עכשיו?</h2></div><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 8 }}><Card><small>תוכנית</small><b style={{ display: "block", fontSize: 19 }}>{money(plan)}</b></Card><Card><small>שולם</small><b style={{ display: "block", fontSize: 19 }}>{money(paid)}</b></Card><Card><small>לפני כניסה</small><b style={{ display: "block", fontSize: 19 }}>{urgent.length}</b></Card></div><Card><h3 style={{ marginTop: 0 }}>חסמים ופעולות</h3>{urgent.length ? urgent.slice(0, 4).map(i => <button key={i.id} onClick={() => select(i)} style={{ width: "100%", textAlign: "start", padding: "12px 0", border: 0, borderBottom: "1px solid #E5EAE6", background: "transparent", font: "inherit" }}><AlertTriangle size={16} color="#A66512" style={{ verticalAlign: "middle", marginInlineEnd: 8 }} />{i.name} · {i.status || "ללא מצב"}</button>) : <p>אין עדיין פריטים שחייבים להיסגר לפני הכניסה.</p>}</Card><Card><h3 style={{ marginTop: 0 }}>תזכורות קרובות</h3>{reminders.length ? reminders.slice(0, 4).map(({ item, date }) => <button key={item.id} onClick={() => select(item)} style={{ width: "100%", textAlign: "start", padding: "10px 0", border: 0, borderBottom: "1px solid #E5EAE6", background: "transparent", font: "inherit" }}><b>{item.name}</b><div style={{ color: "#63716A", fontSize: 14 }}>ב־{date.toLocaleDateString("he-IL")} · {item.reminderNote || "לבדוק מול הספק"}</div></button>) : <p style={{ color: "#63716A", marginBottom: 0 }}>אין תזכורות מתוזמנות. הוסף תזכורת בפריט רכישה.</p>}</Card><Card><h3 style={{ marginTop: 0 }}>לוח המעבר</h3>{data.milestones.map(m => <div key={m.id} style={{ padding: "8px 0", borderBottom: "1px solid #E5EAE6" }}><b>{m.name}</b><span style={{ color: "#A66512", marginInlineStart: 8 }}>{m.status}</span><div style={{ color: "#63716A", fontSize: 14 }}>{m.blocker || m.date || "טרם נקבע"}</div></div>)}</Card></div>;
}
function Items({ data, edit, add, remove }) { return <div style={{ display: "grid", gap: 12 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h2 style={{ margin: 0 }}>תקציב ורכש</h2><span style={{ color: "#63716A" }}>כל רכישה נשמרת פעם אחת</span></div><Btn onClick={add}><Plus size={18} />רכישה</Btn></div>{data.items.length ? data.items.map(i => { const total = Number(i.finalCost || i.estimate || 0), paid = i.payments.reduce((s,p)=>s+Number(p.amount||0),0); return <Card key={i.id}><button onClick={() => edit(i)} style={{ width: "100%", textAlign: "start", border: 0, background: "transparent", font: "inherit", cursor: "pointer" }}><div style={{ display:"flex",justifyContent:"space-between",gap:8 }}><b>{i.name}</b><span style={{ color:"#256B57" }}>{i.status}</span></div><div style={{ color:"#63716A",fontSize:14,marginTop:4 }}>{i.room} · {i.category} · יעד: {i.dueDate || "לא נקבע"}</div><div style={{ display:"flex",justifyContent:"space-between",marginTop:10 }}><span>תוכנית {money(total)}</span><span>יתרה {money(Math.max(0,total-paid))}</span></div></button><div style={{ display:"flex",justifyContent:"space-between",marginTop:10 }}><span>{i.link && <a href={i.link} target="_blank" rel="noreferrer" style={{color:"#256B57"}}><ExternalLink size={15} /> קישור</a>}</span><button onClick={() => remove(i.id)} style={{border:0,background:"transparent",color:"#B53A31",font:"inherit"}}>מחיקה</button></div></Card>; }) : <Card><p>עוד אין רכישות. התחילו בפריט שיש לו זמן אספקה ארוך או שחוסם החלטה.</p><Btn onClick={add}><Plus size={18} />הוספת פריט ראשון</Btn></Card>}</div>; }
function Suppliers({ data, setData }) { const [name,setName]=useState(""); const add=()=>{if(!name.trim())return;setState(setData,d=>({suppliers:[...d.suppliers,{...emptySupplier(),name:name.trim()}]}));setName("");};return <div style={{display:"grid",gap:12}}><h2 style={{margin:0}}>ספקים</h2><Card><div style={{display:"flex",gap:8}}><input placeholder="שם ספק או בעל מקצוע" value={name} onChange={e=>setName(e.target.value)} style={input}/><Btn onClick={add}>הוספה</Btn></div></Card>{data.suppliers.map(s=><Card key={s.id}><b>{s.name}</b><div style={{color:"#63716A"}}>{s.trade || "תחום טרם הוזן"}</div></Card>)}{!data.suppliers.length&&<Card>לכל ספק ייקשרו הצעות, הזמנות, תשלומים ומסמכים דרך פריטי השיפוץ.</Card>}</div>; }
function Plan({ data, setData }) { return <div style={{display:"grid",gap:12}}><h2 style={{margin:0}}>תוכנית ולוח זמנים</h2><Card><p style={{marginTop:0,color:"#63716A"}}>המועדים שהוזנו בעבר דורשים אימות שנה ומצב. התראות לא יופעלו עד לאישור.</p>{data.milestones.map((m,i)=><div key={m.id} style={{display:"grid",gridTemplateColumns:"1fr 140px",gap:8,padding:"10px 0",borderBottom:"1px solid #E5EAE6"}}><div><b>{m.name}</b><div style={{color:"#A66512",fontSize:14}}>{m.status}</div></div><input type="date" value={m.date} onChange={e=>setState(setData,d=>({milestones:d.milestones.map((x,j)=>j===i?{...x,date:e.target.value,status:e.target.value?"נקבע":"דורש אימות",blocker:e.target.value?"":"יש לאמת שנה ומועד"}:x)}))} style={input}/></div>)}</Card><Card><h3 style={{marginTop:0}}>סדר עבודה מוצע</h3><ol style={{paddingInlineStart:20,lineHeight:1.8}}><li>מסירה ותיעוד מצב</li><li>מדידות והחלטות</li><li>תשתיות מתואמות</li><li>גמרים והתקנות</li><li>ניקיון, כניסה ובדק</li></ol></Card></div>; }
function Docs({ data, setData }) { return <div style={{display:"grid",gap:12}}><h2 style={{margin:0}}>מסמכים ובדק</h2><Card><Upload size={22} color="#256B57"/><h3>אחסון מסמכים יופעל לאחר חיבור מאובטח</h3><p style={{color:"#63716A"}}>בשלב זה המערכת לא מעלה קבצים. אפשר לרשום מסמך וקישור חיצוני בלבד, כדי למנוע הבטחה שגויה שהקובץ נשמר.</p><Btn secondary onClick={()=>setState(setData,d=>({documents:[...d.documents,{id:crypto.randomUUID(),name:"מסמך חדש",type:"טיוטה",url:""}]}))}>הוספת רישום מסמך</Btn>{data.documents.map(x=><div key={x.id} style={{marginTop:10}}>{x.name} · {x.type}</div>)}</Card><Card><h3 style={{marginTop:0}}>בדק ומסירה</h3><p>בעת מסירה תעדו ליקוי, תמונה, תאריך, אחראי ותאריך תיקון. עבודות חשמל ותשתיות יש לאשר מול בעל מקצוע מוסמך.</p></Card></div>; }
export default function RenovationHQ() {
 const { data: raw, setData, ready } = useStore(STORE_KEY, INIT); const [tab,setTab]=useState("dash"); const [editing,setEditing]=useState(null); const data=useMemo(()=>ensure(raw),[raw]); if(!ready)return <div style={{padding:24}}>טוען את חברת השיפוץ…</div>;
 const save=item=>{setState(setData,d=>{ const customName = item.supplierName?.trim(); let suppliers = d.suppliers || []; let saved = item; if (customName) { const existing = suppliers.find(s => s.name.trim().toLocaleLowerCase() === customName.toLocaleLowerCase()); const supplierId = existing?.id || crypto.randomUUID(); if (!existing) suppliers = [...suppliers, { ...emptySupplier(), id: supplierId, name: customName }]; saved = { ...item, supplierId, supplierName: "" }; } return { suppliers, items:d.items.some(x=>x.id===saved.id)?d.items.map(x=>x.id===saved.id?saved:x):[...d.items,saved] }; });setEditing(null);};
 const remove=id=>setState(setData,d=>({items:d.items.filter(x=>x.id!==id)}));
 const content=tab==="dash"?<Dashboard data={data} select={setEditing}/>:tab==="items"?<Items data={data} edit={setEditing} add={()=>setEditing(emptyItem())} remove={remove}/>:tab==="suppliers"?<Suppliers data={data} setData={setData}/>:tab==="plan"?<Plan data={data} setData={setData}/>:<Docs data={data} setData={setData}/>;
 return <div dir="rtl" style={{fontFamily:"Heebo, Inter, system-ui, sans-serif",color:"#18231E"}}><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr)",gap:16}}><nav aria-label="מחלקות השיפוץ" style={{display:"flex",gap:4,overflowX:"auto",borderBottom:"1px solid #DCE3DE",paddingBottom:8}}>{NAV.map(([id,label])=><button key={id} onClick={()=>setTab(id)} style={{whiteSpace:"nowrap",minHeight:44,border:0,borderRadius:9,padding:"0 12px",background:tab===id?"#E6F0EB":"transparent",color:tab===id?"#1D5A48":"#44514A",font:"inherit",fontWeight:tab===id?700:400}}>{label}</button>)}</nav>{content}</div>{editing&&<ItemEditor item={editing.name?editing:null} suppliers={data.suppliers} onSave={save} onClose={()=>setEditing(null)}/>}</div>;
}