import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, Check, ChevronLeft, CircleDollarSign, Cloud, Database, Dumbbell, HeartHandshake, Home, Plus, RefreshCw, ShieldAlert, TrendingUp, X } from 'lucide-react'
import './App.css'

type DepartmentId = 'money' | 'home' | 'health' | 'career' | 'mind' | 'investments'
type Status = 'critical' | 'recovery' | 'building'
type Department = { id: DepartmentId; name: string; subtitle: string; status: Status; situation: string; nextAction: string; deadline: string; done: boolean }

const initialDepartments: Department[] = [
  { id: 'money', name: 'כספים', subtitle: 'תזרים, התחייבויות, סדר', status: 'critical', situation: 'טרם מולא', nextAction: 'למפות הכנסות, הוצאות והתחייבויות', deadline: 'השבוע', done: false },
  { id: 'home', name: 'בית חדש', subtitle: 'חיפוש, תקציב ומעבר', status: 'recovery', situation: 'טרם מולא', nextAction: 'להגדיר תקציב, אזור ותאריך יעד', deadline: 'השבוע', done: false },
  { id: 'health', name: 'אימון ותזונה', subtitle: 'אנרגיה, גוף ושגרה', status: 'recovery', situation: 'טרם מולא', nextAction: 'לקבוע נקודת פתיחה לשבוע הקרוב', deadline: '48 שעות', done: false },
  { id: 'career', name: 'מציאת עבודה', subtitle: 'כיוון, קורות חיים ופניות', status: 'critical', situation: 'טרם מולא', nextAction: 'לכתוב תמונת מצב של חיפוש העבודה', deadline: 'השבוע', done: false },
  { id: 'mind', name: 'תמיכה נפשית', subtitle: 'פסיכולוג, עומס ותמיכה', status: 'critical', situation: 'טרם מולא', nextAction: 'לאתר או לקבוע שיחה מקצועית', deadline: '48 שעות', done: false },
  { id: 'investments', name: 'השקעות', subtitle: 'מיפוי, מדיניות וסיכון', status: 'recovery', situation: 'טרם מולא', nextAction: 'לרכז תמונת נכסים והתחייבויות', deadline: 'השבוע', done: false },
]
const meta: Record<DepartmentId, { icon: typeof Home; color: string }> = { money: { icon: CircleDollarSign, color: 'gold' }, home: { icon: Home, color: 'sky' }, health: { icon: Dumbbell, color: 'lime' }, career: { icon: BriefcaseBusiness, color: 'coral' }, mind: { icon: HeartHandshake, color: 'violet' }, investments: { icon: TrendingUp, color: 'blue' } }
const statusLabel: Record<Status, string> = { critical: 'דורש חילוץ', recovery: 'בתהליך התאוששות', building: 'בבנייה' }

function App() {
  const [departments, setDepartments] = useState<Department[]>(() => { const saved = localStorage.getItem('personal-hq-departments'); return saved ? JSON.parse(saved) : initialDepartments })
  const [selected, setSelected] = useState<Department | null>(null)
  const [weeklyNote, setWeeklyNote] = useState(() => localStorage.getItem('personal-hq-note') || '')
  const [activeView, setActiveView] = useState<'hq' | 'review'>('hq')
  const [showConnection, setShowConnection] = useState(false)
  useEffect(() => localStorage.setItem('personal-hq-departments', JSON.stringify(departments)), [departments])
  useEffect(() => localStorage.setItem('personal-hq-note', weeklyNote), [weeklyNote])
  const urgent = useMemo(() => departments.filter((d) => d.status === 'critical' && !d.done), [departments])
  const complete = departments.filter((d) => d.done).length
  const updateDepartment = (updated: Department) => { setDepartments((list) => list.map((item) => item.id === updated.id ? updated : item)); setSelected(updated) }
  return <main dir="rtl" className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">מ</span><span>מטה אישי</span></div><div className="topbar-actions"><button className="data-button" onClick={() => setShowConnection(true)}><Database size={15} />חיבור נתונים</button><div className="topbar-status"><span className="pulse" />מצב הקמה מחדש</div></div></header>
    <section className="hero-panel"><div><p className="eyebrow">לוח המנכ״ל · ספטמבר 2026</p><h1>לא לנהל לבד.<br /><em>לבנות מחדש, ביחד.</em></h1><p className="hero-copy">מקום אחד שרואה את כל התמונה, מציף סכנות, ומתרגם עומס לצעד הבא.</p></div><div className="score"><span>{complete}/6</span><small>צעדי התאוששות<br />נסגרו</small></div></section>
    <nav className="nav-tabs" aria-label="ניווט"><button className={activeView === 'hq' ? 'active' : ''} onClick={() => setActiveView('hq')}>לוח מצב</button><button className={activeView === 'review' ? 'active' : ''} onClick={() => setActiveView('review')}>ישיבת הנהלה</button></nav>
    {activeView === 'hq' ? <><>{urgent.length > 0 && <section className="alert-strip"><ShieldAlert size={19} /><span><strong>{urgent.length} תחומים</strong> דורשים התערבות קרובה. מתחילים בצעד קטן אחד בכל תחום.</span></section>}</><section className="section-heading"><div><p className="eyebrow">החטיבות שלך</p><h2>תכנית התאוששות</h2></div><span>{departments.length} תחומים</span></section><section className="department-grid">{departments.map((department) => { const Icon = meta[department.id].icon; return <button key={department.id} className={`department-card ${department.done ? 'done' : ''}`} onClick={() => setSelected(department)}><div className="card-top"><span className={`icon-box ${meta[department.id].color}`}><Icon size={20} /></span><span className={`status-dot ${department.status}`}>{department.done ? 'הושלם' : statusLabel[department.status]}</span></div><div className="card-title"><h3>{department.name}</h3><p>{department.subtitle}</p></div><div className="next-action"><span>הצעד הבא</span><strong>{department.nextAction}</strong></div><div className="card-footer"><span>{department.deadline}</span><ChevronLeft size={18} /></div></button>})}</section><button className="quick-add" onClick={() => setSelected(departments[0])}><Plus size={20} />עדכון חדש למטה</button></> : <Review note={weeklyNote} setNote={setWeeklyNote} departments={departments} onOpen={setSelected} />}
    {selected && <DepartmentDialog department={selected} onClose={() => setSelected(null)} onSave={updateDepartment} />}{showConnection && <SupabaseConnection onClose={() => setShowConnection(false)} />}<footer>הנתונים נשמרים במכשיר הזה בלבד</footer>
  </main>
}
function Review({ note, setNote, departments, onOpen }: { note: string; setNote: (value: string) => void; departments: Department[]; onOpen: (d: Department) => void }) { const critical = departments.filter((d) => d.status === 'critical' && !d.done); return <section className="review"><p className="eyebrow">20 דקות · פעם בשבוע</p><h2>ישיבת הנהלה אישית</h2><div className="review-card"><div className="review-number">01</div><div><h3>מה עלול להישבר קודם?</h3><p>לא כדי להילחץ—כדי שהמטה ידע איפה להתערב.</p>{critical.map((d) => <button className="text-link" key={d.id} onClick={() => onOpen(d)}>{d.name} <ArrowLeft size={15} /></button>)}</div></div><div className="review-card"><div className="review-number">02</div><div><h3>מה נחסם, ומי יכול לעזור?</h3><p>עזרה היא משאב ניהולי: איש מקצוע, חבר, בן משפחה או גוף חיצוני.</p></div></div><div className="review-card note-card"><div className="review-number">03</div><div><h3>סיכום המנכ״ל לשבוע</h3><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="מה קרה השבוע? מה ההחלטה האחת שאני לוקח/ת הלאה?" /></div></div></section> }
function DepartmentDialog({ department, onClose, onSave }: { department: Department; onClose: () => void; onSave: (d: Department) => void }) { const [draft, setDraft] = useState(department); const change = (field: keyof Department, value: string | boolean) => setDraft({ ...draft, [field]: value } as Department); return <div className="overlay" role="dialog" aria-modal="true"><div className="dialog"><div className="dialog-head"><div><p className="eyebrow">חטיבה אישית</p><h2>{draft.name}</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><label>מה קורס או תקוע עכשיו?<textarea value={draft.situation} onChange={(e) => change('situation', e.target.value)} /></label><label>צעד ההתאוששות הבא<input value={draft.nextAction} onChange={(e) => change('nextAction', e.target.value)} /></label><div className="two-inputs"><label>מועד קרוב<input value={draft.deadline} onChange={(e) => change('deadline', e.target.value)} /></label><label>מצב<select value={draft.status} onChange={(e) => change('status', e.target.value)}><option value="critical">דורש חילוץ</option><option value="recovery">בתהליך התאוששות</option><option value="building">בבנייה</option></select></label></div><button className={`completion ${draft.done ? 'is-done' : ''}`} onClick={() => change('done', !draft.done)}>{draft.done ? <Check size={18} /> : <AlertTriangle size={18} />}{draft.done ? 'הצעד הושלם' : 'לסמן שהצעד הושלם'}</button><button className="save-button" onClick={() => { onSave(draft); onClose() }}><RefreshCw size={18} />שמירת עדכון</button></div></div> }
function SupabaseConnection({ onClose }: { onClose: () => void }) {
  const saved = JSON.parse(localStorage.getItem('personal-hq-supabase') || '{}') as { url?: string; key?: string }
  const [url, setUrl] = useState(saved.url || '')
  const [key, setKey] = useState(saved.key || '')
  const [result, setResult] = useState<'idle' | 'checking' | 'success' | 'error'>('idle')
  const test = async () => { setResult('checking'); try { const response = await fetch(`${url.replace(/\/$/, '')}/rest/v1/`, { headers: { apikey: key } }); if (!response.ok) throw new Error(); localStorage.setItem('personal-hq-supabase', JSON.stringify({ url, key })); setResult('success') } catch { setResult('error') } }
  return <div className="overlay" role="dialog" aria-modal="true"><div className="dialog connection-dialog"><div className="dialog-head"><div><p className="eyebrow">שכבת הנתונים</p><h2><Cloud size={22} />חיבור Supabase</h2></div><button className="icon-button" onClick={onClose}><X /></button></div><p className="connection-copy">הפרטים נשמרים רק בדפדפן במכשיר הזה. אין להכניס כאן מפתח <strong>service_role</strong>.</p><label>Project URL<input dir="ltr" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://xxxxx.supabase.co" /></label><label>Publishable / anon key<input dir="ltr" type="password" value={key} onChange={(e) => setKey(e.target.value)} placeholder="sb_publishable_..." /></label><button className="save-button" disabled={!url || !key || result === 'checking'} onClick={test}>{result === 'checking' ? 'בודק חיבור…' : 'בדיקה ושמירת חיבור'}</button>{result === 'success' && <p className="connection-result success"><Check size={17} />החיבור נשמר במכשיר הזה. השלב הבא: יצירת טבלאות וסנכרון.</p>}{result === 'error' && <p className="connection-result error"><AlertTriangle size={17} />לא הצלחתי להתחבר. יש לבדוק את הכתובת ואת המפתח הציבורי.</p>}</div></div>
}
export default App
